config/routes.rb
Rails.application.routes.draw do

  namespace :user do
  get 'users/show'
  end

  namespace :user do
  get 'users/index'
  end

  namespace :user do
  get 'users/destroy'
  end

  namespace :user do
  get 'users/new'
  end

  namespace :user do
  get 'users/create'
  end

  namespace :user do
  get 'mobilephones/show'
  end

  namespace :user do
  get 'mobilephones/index'
  end

  namespace :user do
  get 'mobilephones/destroy'
  end

  namespace :user do
  get 'mobilephones/new'
  end

  namespace :user do
  post 'mobilephones/create'
  end

  namespace :user do
  get 'certificates/show'
  end

  namespace :user do
  get 'certificates/index'
  end

  namespace :user do
  get 'certificates/destroy'
  end

  namespace :user do
  get 'certificates/new'
  get 'certificates/download_ca'
  end

  namespace :user do
  post 'certificates/create'
  end

  namespace :user do
  get 'nfcs/show'
  end

  namespace :user do
  get 'nfcs/index'
  end

  namespace :user do
  get 'nfcs/destroy'
  end

  namespace :user do
  get 'nfcs/new'
  end

  namespace :user do
  get 'nfcs/create'
  end

  get 'user/create'

  get 'user/new'

  get 'user/edit'

  get 'user/show'

  get 'user/update'

  get 'user/destroy'

  devise_for :users

end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/encoder.rb
class Encoder < ActiveRecord::Base
  def self.generate_ca
    '呵呵'
  end
end

app/models/filekey.rb
class Filekey < ActiveRecord::Base
end

app/models/pending.rb
class Pending < ActiveRecord::Base
  dragonfly_accessor :qr

  def self.generate_pending_action(user, action: nil, obj: nil, msg: nil)
    pending = Pending.new(user_id: user.id, enable: true)
    # message = "1" + "*" + action + "*" + objbnm
    message = msg
    qr_code_img = self.generate_qr(message)
    pending.update_attribute :qr, qr_code_img.to_string
    pending
  end

  def self.generate_qr(info)
    RQRCode::QRCode.new( info, :size => 4, :level => :h ).to_img.resize(400,400)
  end
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  has_many :certificates, inverse_of: :user, dependent: :destroy
  has_many :mobilephones, inverse_of: :user, dependent: :destroy
  has_many :nfcs, inverse_of: :user, dependent: :destroy

end

app/models/user/certificate.rb
class User::Certificate < ActiveRecord::Base
  belongs_to :user, inverse_of: :certificates

  def self.authorize_certificate(user, certificate)
    if user.certificates.where(cainfo: certificate)
      true
    else
      false
    end
  end
end

app/models/user/mobilephone.rb
class User::Mobilephone < ActiveRecord::Base
  belongs_to :user, inverse_of: :mobilephones

  def self.bind_mobile(temp_action_id)
    temp_action = Action.find(temp_action_id)
    while temp_action and temp_action.state == 0
      temp_action = Action.find(temp_action_id)
      sleep(3000)
    end
    if temp_action.state == 1
      Action.delete.where(id: temp_action_id)
      true
    else
      false
    end
  end
end

app/models/user/nfc.rb
class User::Nfc < ActiveRecord::Base
  belongs_to :user, inverse_of: :nfcs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'rqrcode_png'

  protect_from_forgery with: :exception

  def first_use?
    return if current_user.nil?
    unbind_devise_number = 0
    user = current_user
    unbind_devise_number += 1 if user.nfcs.count == 0
    unbind_devise_number += 1 if user.mobilephones.count == 0
    unbind_devise_number += 1 if user.certificates.count == 0
    if unbind_devise_number >= 2
      true
    else
      false
    end
  end
end

app/controllers/user/certificates_controller.rb
class User::CertificatesController < ApplicationController
  def show
  end

  def index
    @certificates = current_user.certificates
  end

  def destroy
  end

  def new
  end

  def create
    if first_use?
      @ca = current_user.certificates.build(user: current_user, cainfo: Encoder.generate_ca, state: 1)
      if @ca.save
        redirect_to user_certificates_new_path, notice: '数字证书生成成功，请安装并检验是否绑定成功'
      else
        render 'new'
      end
    else
      # 绑定失败
    end
  end

  def download_ca
    send_file(
        "#{Rails.root}/public/ca/User_CA.cer",
        filename: "User_CA.cer",
    )
  end
end

app/controllers/user/mobilephones_controller.rb
class User::MobilephonesController < ApplicationController
  def show
  end

  def index
    @mobiles = current_user.mobilephones
  end

  def destroy
  end

  def new
  end

  def create
    @action = Pending.generate_pending_action(current_user, "bind", "mobilephone")
    unless @action.save
      render 'new'
    end

=begin
    pre_count = current_user.mobilephones.count
    while Pending.find(@action.id).enable
      if current_user.mobilephones.count - pre_count == 1
        redirect_to user_mobilephonew_new_path, notice: '手机绑定成功'
      end
      #sleep(100)
    end
=end

  end
end

app/controllers/user/nfcs_controller.rb
class User::NfcsController < ApplicationController
  def show
  end

  def index
    @nfcs = current_user.nfcs
  end

  def destroy
  end

  def new
  end

  def create
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
  end

  def index
  end

  def destroy
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def first_use?
    return if current_user.nil?
    unbind_devise_number = 0
    user = current_user
    unbind_devise_number += 1 if user.nfcs.count == 0
    unbind_devise_number += 1 if user.mobilephones.count == 0
    unbind_devise_number += 1 if user.certificates.count == 0
    if unbind_devise_number >= 2
      true
    else
      false
    end
  end

  def get_first_use_url
    unless current_user.nil? or not first_use?
      user_certificates_new_path
    end
  end
end

app/helpers/user/certificates_helper.rb
module User::CertificatesHelper
end

app/helpers/user/mobilephones_helper.rb
module User::MobilephonesHelper
end

app/helpers/user/nfcs_helper.rb
module User::NfcsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/layouts/_footer.html.erb
<hr class="featurette-divider">
<!-- FOOTER -->
<footer>
  <p class="pull-right"><a href="#" style="font-size: 20px">返回顶层</a></p>
  <p style="font-size: 20px">Copyright： <a href="＃" style="font-size: 20px"> 海·创 </a></p>
</footer>

app/views/layouts/_header.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-interval="5000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="/images/home/1.jpg" style="width:100%" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1 style="font-size: 60px">安全便捷的身份验证系统</h1>
          <p></p>
          <p><a class="btn btn-lg btn-primary" data-target="#firstbind" data-toggle="modal" style="width:150px">开始体验</a>
          </p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/images/home/2.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1 style="font-size: 60px">三角相互制约</h1>
          <p style="font-size: 40px">充分保护用户信息的安全性</p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/images/home/3.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption">
          <h1 style="font-size: 60px">使用便捷</h1>
          <p style="font-size: 40px">绑定解绑轻松完成</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>
<!-- /.carousel -->

app/views/layouts/_modals.html.erb
<%if current_user%>
    <div id="nfc" class="modal fade" role="dialog" xmlns="http://www.w3.org/1999/html">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">×</a>
            <h3  style="text-align: center">请用已绑定的手机扫描二维码</h3>
          </div>
          <div class="modal-body" style="text-align: center">
            <%@action = Pending.generate_pending_action(current_user, msg: "1>bind>nfc>1")%>
            <%= image_tag @action.qr.url%>
          </div>
          <div class="modal-footer" style="text-align: center">
            <button class="btn-lg btn-success" data-dismiss="modal">我已完成绑定</button>
          </div>
        </div>
      </div>
    </div>

    <div id="firstbind" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">×</a>
            <h3  style="text-align: center">请先下载安装数字证书<br>再用移动端软件扫描下方二维码</h3>
          </div>
          <div class="modal-body" style="text-align: center">
            <%@action = Pending.generate_pending_action(current_user, msg: "1>register>asdfghjkl")%>
            <%= image_tag @action.qr.url%>
          </div>
          <div class="modal-footer" style="text-align: center">
            <p><a class="btn btn-lg btn-warning" href=<%= user_certificates_download_ca_path %>>下载数字证书</a></p>
          </div>
        </div>
      </div>
    </div>

    <div id="unbind" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">×</a>
            <h3  style="text-align: center">请用已绑定的手机扫描下方二维码</h3>
          </div>
          <div class="modal-body" style="text-align: center">
            <%@action = Pending.generate_pending_action(current_user, msg: "1>unbind>nfc>1")%>
            <%= image_tag @action.qr.url%>
          </div>
          <div class="modal-footer" style="text-align: center">
            <button class="btn-lg btn-success" data-dismiss="modal">我已完成解绑</button>
          </div>
        </div>
      </div>
    </div>

    <div id="warning" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <a class="close" data-dismiss="modal">×</a>
            <h1  style="text-align: center">绑定失败</h1>
          </div>
          <div class="modal-body" style="text-align: center">
            <h2>请用已绑定的PC设备进行操作！</h2>
          </div>
          <div class="modal-footer" style="text-align: center">
            <button class="btn-lg btn-danger" data-dismiss="modal">操作失败</button>
          </div>
        </div>
      </div>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= viewport_meta_tag %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="navbar-brand" href=<%= page_path('home') %>>火眼金睛</a>
  </div>
  <ul class= "nav navbar-nav pull-right">
      <%unless user_signed_in?%>
          <li>
            <%= link_to('注册', new_user_registration_path) %>
          </li>
          <li>
            <%= link_to('登录', new_user_session_path)%>
          </li>
      <%else%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">我的信息<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="<%= user_users_show_path%>">个人信息</a></li>
              <li><a href="#">我绑定的PC</a></li>
              <li><a href="#">我绑定的手机</a></li>
              <li><a href="#">我绑定的NFC</a></li>
              <li class="divider"></li>
              <li><a href="#">用户日志</a></li>
              <li><a href="#">系统设置</a></li>
            </ul>
          </li>
          <li>
            <%= link_to('退出登录', destroy_user_session_path, method: :delete)%>
          </li>
      <%end%>
    </ul>
</div>

  <!--
  <%if notice%>
    <p class="notice"><%= notice %></p>
  <%end%>
  <%if alert%>
    <p class="alert"><%= alert %></p>
  <%end%>
  -->
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>火眼金睛</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>

<%=render 'layouts/header'%>


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-md-4 text-center">
      <img class="img"  style="height:200px;width:260px" src="/images/home/mac.jpg">
      <h1>个人电脑</h1>
      <p style="font-size: 22px">下载数字证书，绑定个人电脑</p>
      <p><a class="btn btn-default" href=<%= user_certificates_download_ca_path %>>绑定PC »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img"  style="height:200px;width:190px" src="/images/home/iphone.png">
      <h1>移动设备</h1>
      <p style="font-size: 22px">绑定移动终端，验证用户身份</p>
      <p><a class="btn btn-default" data-target="#warning" data-toggle="modal">绑定手机 »</a></p>
    </div>
    <div class="col-md-4 text-center">
      <img class="img"  style="height:200px;width:200px" src="/images/home/nfc.png">
      <h1>NFC智能手环</h1>
      <p style="font-size: 22px">绑定NFC设备，辅助移动终端</p>
      <p><a class="btn btn-default" data-target="#nfc" data-toggle="modal">绑定NFC »</a></p>
    </div>
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="/images/home/icon_pc.png" style="height:300px;width:300px">
    <h2 class="featurette-heading">个人电脑  <span class="text-muted" style="font-size: 30px">利用数字证书认证</span></h2>
    <p class="lead">利用CA数字证书，确保对个人电脑的唯一性认证。只有用户绑定的电脑才具有合法的用户权限。能有有效确保信息的安全，使得个人电脑成为用户信息安全的重要屏障</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-left" src="/images/home/icon_mobile.png" style="height:300px;width:300px">
    <h2 class="featurette-heading">移动终端  <span class="text-muted" style="font-size: 30px">利用软硬件信息认证</span></h2>
    <p class="lead">利用移动终端软硬件信息，确保只有用户绑定的移动终端才具有合法的用户权限。利用移动终端便携的特点，方便用户使用多种功能，是本系统保护的重点对象。配合其他两角，形成制约，限制并防止其丢失造成的后果</p>
  </div>

  <hr class="featurette-divider">

  <div class="featurette">
    <img class="featurette-image img-circle pull-right" src="/images/home/icon_nfc.png" style="height:300px;width:300px">
    <h2 class="featurette-heading">NFC智能手环  <span class="text-muted" style="font-size: 30px">可穿戴设备形成第二道屏障</span></h2>
    <p class="lead">可穿戴设备作为另一道重要屏障，在移动终端功能使用的同时提供限制。有效防止移动终端丢失或被盗用的情况发生。同时也不失使用的便捷性</p>
  </div>

  <!-- /END THE FEATURETTES -->
  <%=render 'layouts/footer'%>
</div><!-- /.container -->

<%=render 'layouts/modals'%>
	<!-- script references -->

	</body>
</html>

app/views/user/certificates/destroy.html.erb
<h1>User::Certificates#destroy</h1>
<p>Find me in app/views/user/certificates/destroy.html.erb</p>

app/views/user/certificates/index.html.erb
<h1>我的PC设备</h1>
<% @certificates.each do |pc| %>
    <li><%=pc.cainfo%></li>
<% end %>

app/views/user/certificates/new.html.erb
<%=render 'layouts/header'%>
<h1>绑定PC</h1>
<p>请下载并安装数字证书</p>
<%= form_for :certificate, url: user_certificates_create_path do |f| %>
    <p>
      <%= f.submit "下载数字证书"%>
    </p>
<% end %>
<button class="btn-primary" onclick="">我已安装</button>

app/views/user/certificates/show.html.erb
<h1>User::Certificates#show</h1>
<p>Find me in app/views/user/certificates/show.html.erb</p>

app/views/user/mobilephones/create.html.erb
<%= image_tag @action.qr.url%>

app/views/user/mobilephones/destroy.html.erb
<h1>User::Mobilephones#destroy</h1>
<p>Find me in app/views/user/mobilephones/destroy.html.erb</p>

app/views/user/mobilephones/index.html.erb
<h1>我的手机设备</h1>
<% @mobiles.each do |mobile| %>
    <li><%=mobile.devicename%></li>
<% end %>

app/views/user/mobilephones/new.html.erb
<h1>绑定手机</h1>
<%= form_for :mobilephones, url: user_mobilephones_create_path do |f| %>
    <p>
      <%= f.submit "绑定手机"%>
    </p>
<% end %>

app/views/user/mobilephones/show.html.erb
<h1>User::Mobilephones#show</h1>
<p>Find me in app/views/user/mobilephones/show.html.erb</p>

app/views/user/nfcs/create.html.erb
<h1>User::Nfcs#create</h1>
<p>Find me in app/views/user/nfcs/create.html.erb</p>

app/views/user/nfcs/destroy.html.erb
<h1>User::Nfcs#destroy</h1>
<p>Find me in app/views/user/nfcs/destroy.html.erb</p>

app/views/user/nfcs/index.html.erb
<h1>我的NFC设备</h1>
<% @nfcs.each do |nfc| %>
    <li><%=nfc.devicename%></li>
<% end %>

app/views/user/nfcs/new.html.erb
<h1>User::Nfcs#new</h1>
<p>Find me in app/views/user/nfcs/new.html.erb</p>

app/views/user/nfcs/show.html.erb
<h1>User::Nfcs#show</h1>
<p>Find me in app/views/user/nfcs/show.html.erb</p>

app/views/user/users/create.html.erb
<h1>User::Users#create</h1>
<p>Find me in app/views/user/users/create.html.erb</p>

app/views/user/users/destroy.html.erb
<h1>User::Users#destroy</h1>
<p>Find me in app/views/user/users/destroy.html.erb</p>

app/views/user/users/new.html.erb
<h1>User::Users#new</h1>
<p>Find me in app/views/user/users/new.html.erb</p>

app/views/user/users/show.html.erb
<%= render 'layouts/header'%>
<div class="container">
  <div class="row">
    <div class="col-md-8" id="leftInfo">
      <div id="myNav">
        <ul class="nav nav-pills nav-justified" role="tablist" id="myTab">
          <li class="active"><a href="#pc" role="tab" data-toggle="tab">PC</a></li>
          <li><a href="#mobile" role="tab" data-toggle="tab">Mobile</a></li>
          <li><a href="#nfc" role="tab" data-toggle="tab">NFC</a></li>
        </ul>
      </div>

      <div class="tab-content">

        <div class="tab-pane active" id="pc">
          <div class="pcGroup">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapsePC1" aria-expanded="false" aria-controls="collapseExample">
              绑定的PC 1
            </button>
            <div class="collapse" id="collapsePC1">
              <div class="well">
                <ul class="list-group">
                  <li class="list-group-item">PC名称
                    <p class="detail">My Mac</p></li>
                  <li class="list-group-item">制造商
                    <p class="detail">Apple</p></li>
                  <li class="list-group-item">型号
                    <p class="detail">Macbook Pro C02N93</p></li>
                  <li class="list-group-item">绑定日期
                    <p class="detail">2015-5-20</p></li>
                </ul>
                <button class="btn btn-lg btn-danger" data-target="#unbind" data-toggle="modal" style="height:70%;width:100%">解绑该设备</button>
              </div>
            </div>
          </div>
        </div>

        <div class="tab-pane fade" id="mobile">
          <div class="pcGroup">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseMobile" aria-expanded="false" aria-controls="collapseExample">
              绑定的手机 1
            </button>
            <div class="collapse" id="collapseMobile">
              <div class="well">
                <ul class="list-group">
                  <li class="list-group-item">手机名称
                    <p class="detail">我的手机</p></li>
                  <li class="list-group-item">制造商
                    <p class="detail">HTC</p></li>
                  <li class="list-group-item">型号
                    <p class="detail">HTC 606w</p></li>
                  <li class="list-group-item">绑定日期
                    <p class="detail">2015-5-20</p></li>
                </ul>
                <button class="btn btn-lg btn-danger" data-target="#unbind" data-toggle="modal" style="height:70%;width:100%">解绑该设备</button>
              </div>
            </div>
          </div>
        </div>

        <div class="tab-pane fade" id="nfc">
          <div class="pcGroup">
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseNFC" aria-expanded="false" aria-controls="collapseExample">
              绑定的NFC 1
            </button>
            <div class="collapse" id="collapseNFC">
              <div class="well">
                <ul class="list-group">
                  <li class="list-group-item">NFC名称
                    <p class="detail">我的NFC</p></li>
                  <li class="list-group-item">制造商
                    <p class="detail">海创</p></li>
                  <li class="list-group-item">型号
                    <p class="detail">f19179a06954edd0</p></li>
                  <li class="list-group-item">绑定日期
                    <p class="detail">2015-5-20</p></li>
                </ul>
                <button class="btn btn-lg btn-danger" data-target="#unbind" data-toggle="modal" style="height:70%;width:100%">解绑该设备</button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="col-md-4" id="rightInfo">
      <div class="sidebar">
        <div class="iconName">
          <h4 id="name">Sea Create</h4>
          <img id="icon" src="/images/user_show/header.jpeg">
        </div>
        <div class="information">
          <div class="info-list">
            <img class="littleIcon" src="/images/user_show/icon1.png">
            <p id="school">所属机构：四川大学</p>
          </div>
          <div class="info-list">
            <img class="littleIcon" src="/images/user_show/icon2.png">
            <p id="address">所在地点：四川成都</p>
          </div>
          <div class="info-list">
            <img class="littleIcon" src="/images/user_show/icon3.png">
            <p>注册时间：<span id="bindDate">2015-4-1 </span></p>
          </div>
        </div>
      </div>
    </div>

  </div>
  <%= render 'layouts/modals'%>
  <%= render 'layouts/footer'%>
</div>